# -*- coding: utf-8 -*-
"""curate_PRJEB21612.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwjbuSQKUUWh8xpFirlcroC2PoISoKD8
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB62825"
STUDY_ID_ORIGINAL = "PRJEB21612"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB62825 = df_curated[df_curated["Study_ID"] == STUDY_ID]
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB62825["Subject_ID"] = df_curated_PRJEB62825["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB62825["Nucleotide_Type"] = df_curated_PRJEB62825["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJEB21612_data - Sheet1.csv"
supp_data = pd.read_csv(PRJ_supp_data_path, sep=",")
#for D01-D09, I want to get rid of the 0, same with H01-H09

#map ids from supp data to df_curated with age, sex, and whether they have hypertension
#should be yes hypertension if start of ID is D. The subject does not have hypertension if their ID starts with H (indicates healthy)

new_ids = ["H1", "H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9"]
old_ids = ["H01", "H02", "H03", "H04", "H05", "H06", "H07", "H08", "H09", "D01", "D02", "D03", "D04", "D05", "D06", "D07", "D08", "D09"]

for i in range(len(new_ids)):
  supp_data["Sample ID"] = supp_data["Sample ID"].replace({old_ids[i]: new_ids[i]})

sample_accession_sex_map = supp_data.set_index("Sample ID").to_dict()["Sex"]
sample_accession_age_map = supp_data.set_index("Sample ID").to_dict()["Age (y)"]
sample_accesion_lifestyle_map = supp_data.set_index("Sample ID").to_dict()["Smoke (Y/N)"]

df_curated_PRJEB62825["Sex"] = df_curated_PRJEB62825["Subject_ID"].map(sample_accession_sex_map)
df_curated_PRJEB62825["Age"] = df_curated_PRJEB62825["Subject_ID"].map(sample_accession_age_map)
df_curated_PRJEB62825["Lifestyle"] = df_curated_PRJEB62825["Subject_ID"].map(sample_accesion_lifestyle_map)
df_curated_PRJEB62825["Lifestyle"] = df_curated_PRJEB62825["Lifestyle"].replace({"Y": "smoking", "N": "non-smoking"})
df_curated_PRJEB62825["Location"] = "China"

conditions = [
    df_curated_PRJEB62825["Subject_ID"].str.startswith("H", na=False),
    df_curated_PRJEB62825["Subject_ID"].str.startswith("D", na=False)
]

choices = ["healthy", "hypertension"]
df_curated_PRJEB62825["Health_status"] = np.select(conditions, choices, default="unknown")

#add age groups

conditions_age = [
    df_curated_PRJEB62825["Age"].between(0,2),
    df_curated_PRJEB62825["Age"].between(3,5),
    df_curated_PRJEB62825["Age"].between(6,17),
    df_curated_PRJEB62825["Age"].between(18,39),
    df_curated_PRJEB62825["Age"].between(40,64),
    df_curated_PRJEB62825["Age"] >= 65
]

choices_age = ["Infant", "Child", "Adolescent", "Young_adult", "Middle_age", "Elderly"]

df_curated_PRJEB62825["Age_group"] = np.select(conditions_age, choices_age, default="unknown")

df_curated_PRJEB62825.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB62825.csv", index = None)