# -*- coding: utf-8 -*-
"""curate_PRJNA700071.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX7s_W_dhOMrUdIOWiDDHMvRzUkhG6cP
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB65904"
STUDY_ID_ORIGINAL = "PRJNA700071"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB65904 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB65904["Subject_ID"] = df_curated_PRJEB65904["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB65904["Nucleotide_Type"] = df_curated_PRJEB65904["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJNA700071.xlsx"
supp_data = pd.read_excel(PRJ_supp_data_path)

conditions = [
    supp_data["Gender"] == "F",
    supp_data["Gender"] == "M"
]

choices = ["Female", "Male"]

supp_data["Gender"] = np.select(conditions, choices, default="Unknown")
sex_map = supp_data.set_index("Sample_ID").to_dict()["Gender"]
age_map = supp_data.set_index("Sample_ID").to_dict()["Age"]

conditions = [
    supp_data["Category"] == "Asymptomatic",
    supp_data["Category"] == "Positive",
    supp_data["Category"] == "No_Growth",
    supp_data["Category"] == "Insignificant",
    supp_data["Category"] == "Contaminated"
]

choices = ["Healthy", "Urinary Tract Infection", "Urinary Tract Infection", "Urinary Tract Infection", "Urinary Tract Infection"]

supp_data["Category"] = np.select(conditions, choices, default="Unknown")
health_map = supp_data.set_index("Sample_ID").to_dict()["Category"]

df_curated_PRJEB65904["Sex"] = df_curated_PRJEB65904["Subject_ID"].map(sex_map)
df_curated_PRJEB65904["Health_status"] = df_curated_PRJEB65904["Subject_ID"].map(health_map)
df_curated_PRJEB65904["Age"] = df_curated_PRJEB65904["Subject_ID"].map(age_map)
df_curated_PRJEB65904["Body_site"] = "urine"
df_curated_PRJEB65904["Location"] = "USA"


conditions = [
    df_curated_PRJEB65904["Age"].between(0,2),
    df_curated_PRJEB65904["Age"].between(3,5),
    df_curated_PRJEB65904["Age"].between(6,17),
    df_curated_PRJEB65904["Age"].between(18,39),
    df_curated_PRJEB65904["Age"].between(40,64),
    df_curated_PRJEB65904["Age"] >= 65
]

choices = ["Infant", "Child", "Adolescent", "Young_adult", "Middle_age", "Elderly"]

df_curated_PRJEB65904["Age_category"] = np.select(conditions, choices, default="Unknown")

df_curated_PRJEB65904.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB65904.csv", index = None)
