# -*- coding: utf-8 -*-
"""curate_PRJNA397112.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPmloI7VZDfTWFO2IfsIWE4fNJH9kQ0X
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB33179"
STUDY_ID_ORIGINAL = "PRJNA397112"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB33179 = df_curated[df_curated["Study_ID"] == STUDY_ID]
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

#age is available

df_curated_PRJEB33179["Subject_ID"] = df_curated_PRJEB33179["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB33179["Nucleotide_Type"] = df_curated_PRJEB33179["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJNA397112 - Sheet1.csv"
supp_data = pd.read_csv(PRJ_supp_data_path, sep=",")

#left off here, need to remove _3 from C3_M.
#need to also finish converting the ages

df_curated_PRJEB33179["Subject_ID"] = df_curated_PRJEB33179["Subject_ID"].str.split('_').str[0]

#contains age, gender, diet
#LOC 1 = Bhopal
#LOC 2 = Kerala

age_mapping = supp_data.set_index("Sample").to_dict()["Age(Years)"]
sex_mapping = supp_data.set_index("Sample").to_dict()["Gender"]
diet_mapping = supp_data.set_index("Sample").to_dict()["Diet"]

#convert LOC1 and LOC2 to Bhopal and Kerala by using conditions
conditions = [
    supp_data["Location"].str.contains("LOC1"),
    supp_data["Location"].str.contains("LOC2")
]
choices = ["Bhopal", "Kerala"]
supp_data["Location"] = np.select(conditions, choices, default="Other")

location_mapping = supp_data.set_index("Sample").to_dict()["Location"]

#we can map now
df_curated_PRJEB33179["Age"] = df_curated_PRJEB33179["Subject_ID"].map(age_mapping)
df_curated_PRJEB33179["Sex"] = df_curated_PRJEB33179["Subject_ID"].map(sex_mapping)
df_curated_PRJEB33179["Diet"] = df_curated_PRJEB33179["Subject_ID"].map(diet_mapping)
df_curated_PRJEB33179["Location"] = df_curated_PRJEB33179["Subject_ID"].map(location_mapping)

df_curated_PRJEB33179["Health_status"] = "Healthy"

#age category column
age_conditions = [
    df_curated_PRJEB33179["Age"].between(0, 2),
    df_curated_PRJEB33179["Age"].between(3,5),
    df_curated_PRJEB33179["Age"].between(6,17),
    df_curated_PRJEB33179["Age"].between(18,39),
    df_curated_PRJEB33179["Age"].between(40,64),
    df_curated_PRJEB33179["Age"] >= 65
]

age_choices = ["Infant", "Child", "Adolescent", "Young_adult", "Middle_age", "Elderly"]

df_curated_PRJEB33179["Age_category"] = np.select(age_conditions, age_choices, default="unknown")

df_curated_PRJEB33179.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB33179.csv", index = None)