# -*- coding: utf-8 -*-
"""curate_PRJEB60915.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WqVy26DiCKir6aBTXC_vKzRUcLj9BdIu
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB60915"
STUDY_ID_ORIGINAL = "PRJEB35524"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB60915 = df_curated[df_curated["Study_ID"] == STUDY_ID]
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_sra_subject = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL]
nucleotide_mapping = df_sra_subject.set_index("sample_accession").to_dict()["nucleotide_type"]

df_curated_PRJEB60915["Subject_ID"] = df_curated_PRJEB60915["Sample_accession"].map(sample_accession_subject_map)
df_curated_PRJEB60915["Nucleotide_Type"] = df_curated_PRJEB60915["Sample_accession"].map(nucleotide_mapping)

df_curated_PRJEB60915["Health_status"] = "obese and with metabolic syndrome"
df_curated_PRJEB60915["Body_site"] = "feces"
df_curated_PRJEB60915["Body_site_core"] = "gut"

df_curated_PRJEB60915.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB60915.csv", index = None)
