# -*- coding: utf-8 -*-
"""Nguyen_explore_curated_metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABd66-gkI-zqwbqXas_6IEcF83El1-x7
"""

# mount drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated.head()

df_curated[df_curated["Study_ID"] == "PRJEB52172"]

print(df_curated.columns)

for col in df_curated[df_curated["Study_ID"] == "PRJEB52172"].columns:
  print(df_curated[df_curated["Study_ID"] == "PRJEB52172"][col].value_counts())

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Body_site"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Body_site_core"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Health_status"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Diet"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Location"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Lifestyle"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Sex"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Age"].value_counts(dropna=False))

print(df_curated[df_curated["Study_ID"] == "PRJEB52172"]["Nucleotide_Type"].value_counts(dropna=False))

print(df_original.columns)

for col in df_original.columns:
    print(col)

pd.set_option('display.max_rows', 500)
subset = df_original[df_original["study_bioproject"] == "PRJEB52172"]

for col in subset.columns:
    counts = subset[col].value_counts(dropna=True)
    if not counts.empty:
        print(f"\n{'='*10} {col} {'='*10}")
        if len(counts) > 20:
            print(counts.head(20))
            print(f"... Total {len(counts)} unique values")
        else:
            print(counts)

df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_host_sex"]

print(df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_host_sex"].value_counts(dropna=False))

print(df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_body_site"].value_counts(dropna=False))

print(df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_age"].value_counts(dropna=False))

print(df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_diet"].value_counts(dropna=False))

print(df_original[df_original["study_bioproject"] == "PRJEB52172"]["sample_samplemeta_nucleic_acid_extraction"].value_counts(dropna=False))

df_sra.columns

for col in df_sra[df_sra['bioproject'] == "PRJNA433459"].columns:
  print(df_sra[df_sra['bioproject'] == "PRJNA433459"][col].value_counts())

df_sra[df_sra['bioproject'] == "PRJNA433459"]["biosample"].value_counts(dropna=False)

print(df_sra[df_sra['bioproject'] == "PRJNA433459"]["body_site"].value_counts(dropna=False))

df_sra[df_sra['bioproject'] == "PRJNA433459"]["age_years"].value_counts(dropna=False)

df_sra[df_sra['bioproject'] == "PRJNA433459"]["sex"].value_counts(dropna=False)

df_sra[df_sra['bioproject'] == "PRJNA433459"]["diet"].value_counts(dropna=False)

df_sra[df_sra['bioproject'] == "PRJNA433459"]["geo_location"].value_counts(dropna=False)

df_sra[df_sra['bioproject'] == "PRJNA433459"]["lifestyle"].value_counts(dropna=False)

df_sra[df_sra['bioproject'] == "PRJNA433459"]["nucleotide_type"].value_counts(dropna=False)

"""##Lines 93-131


"""

df_sra[df_sra['bioproject'] == " "].values[0]