# -*- coding: utf-8 -*-
"""curate_PRJNA389280.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOOiChyXp1pYXttpMiy5ajTdR2H0YOaQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB42213"
STUDY_ID_ORIGINAL = "PRJNA389280"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB42213 = df_curated[df_curated["Study_ID"] == STUDY_ID]
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"] #[the sample IDs here do not match what is in the manual metadata]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]
# no sex
# no age
# yes subject_id, but there is no supp data to map
df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

keywrd = "G79947"

matches1 = df_sra_subject[df_sra_subject.apply(lambda row: row.astype(str).str.contains("M2025C7_MGX").any(), axis=1)]
matches2 = df_original_s[df_original_s.apply(lambda row: row.astype(str).str.contains("M2025C7_MGX").any(), axis=1)]

df_curated_PRJEB42213["Subject_ID"] = df_curated_PRJEB42213["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB42213["Nucleotide_Type"] = df_curated_PRJEB42213["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

df_curated_PRJEB42213

df_curated_PRJEB42213.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB42213.csv", index = None)