# -*- coding: utf-8 -*-
"""curate_PRJEB15371.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZ7rcDS45RdhyoGLkT3UREirGxs7EepR
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB27122"
STUDY_ID_ORIGINAL = "PRJEB15371"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB27122 = df_curated[df_curated["Study_ID"] == STUDY_ID]
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"] #[the sample IDs here do not match what is in the manual metadata]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]
# no sex
# no age
# no subject_id

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]

target_id = "GZCD005"

#Find if any of the IDs from manual metadata are present in df_original_subject columns
for col in df_original_s.columns:
    if df_original_s[col].astype(str).str.contains(target_id).any():
        print(f"Found match in: {col}")

#for df_sra
for col in df_sra_subject.columns:
    if df_sra_subject[col].astype(str).str.contains(target_id).any():
        print(f"Found match in: {col}")

df_curated_PRJEB27122["Subject_ID"] = df_curated_PRJEB27122["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB27122["Nucleotide_Type"] = df_curated_PRJEB27122["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

#Health status is Crohn's Disease or Healthy control, however mapping is not possible

df_curated_PRJEB27122.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB27122.csv", index = None)