# -*- coding: utf-8 -*-
"""curate_PRJNA715245.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFFJ_9D8vy4Z3CbvrK7xHrqeT5i2s8Dw
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB75554"
STUDY_ID_ORIGINAL = "PRJNA715245"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB75554 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB75554["Subject_ID"] = df_curated_PRJEB75554["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB75554["Nucleotide_Type"] = df_curated_PRJEB75554["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJNA715245 - Sheet1.csv"
supp_data = pd.read_csv(PRJ_supp_data_path)

#we need to edit the subject so that it removes SampleID- and a/b/c.. Gut.fasta
#cut the "-" before SampleID, chop off everything after the last number of the id
df_curated_PRJEB75554["Subject_ID"] = df_curated_PRJEB75554["Subject_ID"].apply(lambda x: x.split("-")[1])
#remove last 10 characters
df_curated_PRJEB75554["Subject_ID"] = df_curated_PRJEB75554["Subject_ID"].apply(lambda x: x[:-10])

df_curated_PRJEB75554["Body_site"] = "feces"
diet_map = supp_data.set_index("Subjects").to_dict()["Antibiotic"]
df_curated_PRJEB75554["Diet"] = df_curated_PRJEB75554["Subject_ID"].map(diet_map)
df_curated_PRJEB75554["Location"] = "USA"

df_curated_PRJEB75554.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB75554.csv", index = None)
