# -*- coding: utf-8 -*-
"""curate_PRJEB17643.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ootLShwNwzMqcn2-caORSa2g46zMO1zH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB60912"
STUDY_ID_ORIGINAL = "PRJEB17643"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB60912 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB60912["Subject_ID"] = df_curated_PRJEB60912["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB60912["Nucleotide_Type"] = df_curated_PRJEB60912["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])
df_curated_PRJEB60912["Location"] = "Israel"
df_curated_PRJEB60912["Body_site"] = "feces"
df_curated_PRJEB60912["Health_status"] = "Healthy"
df_curated_PRJEB60912["Age_category"] = "Young_adult,Middle_age,Elderly"
df_curated_PRJEB60912["Diet"] = df_curated_PRJEB60912["Subject_ID"].str.split("_").str[2]
df_curated_PRJEB60912["Diet"] = df_curated_PRJEB60912["Diet"].replace({"Srdgh" : "Sourdough Bread", "White" : "White Bread"})
df_curated_PRJEB60912["Body_site_core"] = "gut"

df_curated_PRJEB60912.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB60912.csv", index = None)
