# -*- coding: utf-8 -*-
"""curate_PRJEB50505.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdxPGpRXRGpyLxGMULmmrV3kiurAmZyj
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB62833"
STUDY_ID_ORIGINAL = "PRJEB50505"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB62833 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB62833["Subject_ID"] = df_curated_PRJEB62833["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB62833["Nucleotide_Type"] = df_curated_PRJEB62833["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

#PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJEB50505.xlsx"
#supp_data = pd.read_excel(PRJ_supp_data_path)

df_curated_PRJEB62833["Health_status"] = "Healthy"
df_curated_PRJEB62833["Location"] = "Europe"
df_curated_PRJEB62833["Lifestyle"] = "moderate sleep disturbances"
df_curated_PRJEB62833["Age_category"] = "Young_adult, Middle_age"
#no mapping for placebo or receiving dairy-based treatment

df_curated_PRJEB62833.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB62833.csv", index = None)