# -*- coding: utf-8 -*-
"""curate_PRJNA289586.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1bYzPWsoIbW1F5k7qUrhl6tSQsEMG4E
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB22368"
STUDY_ID_ORIGINAL = "PRJNA289586"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB22368 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB22368["Subject_ID"] = df_curated_PRJEB22368["Sample_accession"].map(sample_accession_subject_map)
df_curated_PRJEB22368["Nucleotide_Type"] = df_curated_PRJEB22368["Sample_accession"].map(sample_accession_nucleotide_map)

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJNA289586.xlsx"
supp_data = pd.read_excel(PRJ_supp_data_path)

df_curated_PRJEB22368["Subject_ID"] = df_curated_PRJEB22368["Subject_ID"].str.split("-").str[0]

health_status_map = supp_data.set_index("INDIV").to_dict()["DIABETESTY1"]
age_map = supp_data.set_index("INDIV").to_dict()["AGE"]
lifestyle_map = supp_data.set_index("INDIV").to_dict()["OCCUPATION"]

df_curated_PRJEB22368["Health_status"] = df_curated_PRJEB22368["Subject_ID"].map(health_status_map)
df_curated_PRJEB22368["Age"] = df_curated_PRJEB22368["Subject_ID"].map(age_map)
df_curated_PRJEB22368["Lifestyle"] = df_curated_PRJEB22368["Subject_ID"].map(lifestyle_map)
df_curated_PRJEB22368["Health_status"] = df_curated_PRJEB22368["Health_status"].replace("Yes", "Type 1 Diabetes")
df_curated_PRJEB22368["Health_status"] = df_curated_PRJEB22368["Health_status"].replace("No", "No Type 1 Diabetes")

age_conditions = [
    df_curated_PRJEB22368["Age"].between(0,2),
    df_curated_PRJEB22368["Age"].between(3,5),
    df_curated_PRJEB22368["Age"].between(6,17),
    df_curated_PRJEB22368["Age"].between(18,39),
    df_curated_PRJEB22368["Age"].between(40,64),
    df_curated_PRJEB22368["Age"] >= 65
]

age_choices = ["Infant", "Child", "Adolescent", "Young_adult", "Middle_age", "Elderly"]

df_curated_PRJEB22368["Age_category"] = np.select(age_conditions, age_choices, default="unknown")
df_curated_PRJEB22368["Age_category"] = df_curated_PRJEB22368["Age_category"].replace("unknown", np.nan)

df_curated_PRJEB22368.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB22368.csv", index = None)