# -*- coding: utf-8 -*-
"""curate_PRJNA547717.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exmU93PT923gwmJBIRMoLUDTebK1ST0E
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB43277"
STUDY_ID_ORIGINAL = "PRJNA547717"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB43277 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB43277["Subject_ID"] = df_curated_PRJEB43277["Sample_accession"].apply(lambda x: sample_accession_subject_map[x])
df_curated_PRJEB43277["Nucleotide_Type"] = df_curated_PRJEB43277["Sample_accession"].apply(lambda x: sample_accession_nucleotide_map[x])

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJNA547717.xlsx"
supp_data = pd.read_excel(PRJ_supp_data_path)

sample_accession_bodysite_map = supp_data.set_index("sampleID").to_dict()["body_site"]
sample_accession_healthstatus_map = supp_data.set_index("sampleID").to_dict()["study_group"]
sample_accession_agecat_map = supp_data.set_index("sampleID").to_dict()["age_category"]
sample_accession_lifestyle_map = supp_data.set_index("sampleID").to_dict()["smoker"]

df_curated_PRJEB43277["Body_site"] = df_curated_PRJEB43277["Subject_ID"].map(sample_accession_bodysite_map)
df_curated_PRJEB43277["Age_category"] = "Young_adult,Middle_age,Elderly"
df_curated_PRJEB43277["Health_status"] = df_curated_PRJEB43277["Subject_ID"].map(sample_accession_healthstatus_map)
df_curated_PRJEB43277["Location"] = "Italy"
df_curated_PRJEB43277["Lifestyle"] = df_curated_PRJEB43277["Subject_ID"].map(sample_accession_lifestyle_map)
#SP_385SPT_T016 has diabetes, peri-implantitis
#SP_385SPI_T016 has diabetes, peri-implantitis
#SP_303SPI_T016 has diabetes, peri-implantitis
#SP_133SPT_T016 has diabetes, is healthy
#SP_303SPT_T016 has diabetes, peri-implantitis

df_curated_PRJEB43277.loc[df_curated_PRJEB43277["Subject_ID"] == "SP_385SPT_T016", "Health_status"] = "peri-implantitis,diabetes"
df_curated_PRJEB43277.loc[df_curated_PRJEB43277["Subject_ID"] == "SP_385SPI_T016", "Health_status"] = "peri-implantitis,diabetes"
df_curated_PRJEB43277.loc[df_curated_PRJEB43277["Subject_ID"] == "SP_303SPI_T016", "Health_status"] = "peri-implantitis,diabetes"
df_curated_PRJEB43277.loc[df_curated_PRJEB43277["Subject_ID"] == "SP_133SPT_T016", "Health_status"] = "healthy, diabetes"
df_curated_PRJEB43277.loc[df_curated_PRJEB43277["Subject_ID"] == "SP_303SPT_T016", "Health_status"] = "peri-implantitis,diabetes"

df_curated_PRJEB43277["Lifestyle"] = df_curated_PRJEB43277["Lifestyle"].replace({"yes": "smoker", "no": "non-smoker"})
df_curated_PRJEB43277["Body_site_core"] = "oral"

df_curated_PRJEB43277.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB43277.csv", index = None)