# -*- coding: utf-8 -*-
"""curate_PRJEB42572.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbPDf4OmvG20owf8qDSEJHSrYaYHj5C_
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sra_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/cleaned_sra_metadata.tsv"
curated_cleaned_path = "/content/drive/Shareddrives/Meta2/Metadata/curated_metadata.csv"
original_metadata_path = "/content/drive/Shareddrives/Meta2/Data/hmb_assemblies_metadata.csv"
STUDY_ID = "PRJEB64259"
STUDY_ID_ORIGINAL = "PRJEB42572"

df_sra = pd.read_csv(sra_cleaned_path, sep="\t")
df_curated = pd.read_csv(curated_cleaned_path, sep=",")
df_original = pd.read_csv(original_metadata_path, sep=",")

df_curated_PRJEB64259 = df_curated[df_curated["Study_ID"] == STUDY_ID].copy()
df_original_subject = df_original[df_original["study_bioproject"] == STUDY_ID][["sample_accession", "sample_sample-name"]]
sample_accession_subject_map = df_original_subject.set_index("sample_accession").to_dict()["sample_sample-name"]
sample_accession_nucleotide_map = df_sra[df_sra["bioproject"] == STUDY_ID_ORIGINAL][["sample_accession", "nucleotide_type"]].set_index("sample_accession").to_dict()["nucleotide_type"]

df_original_s = df_original[df_original["study_bioproject"] == STUDY_ID]
df_sra_subject = df_sra[df_sra['bioproject'] == STUDY_ID_ORIGINAL]

df_curated_PRJEB64259["Subject_ID"] = df_curated_PRJEB64259["Sample_accession"].map(sample_accession_subject_map)
df_curated_PRJEB64259["Nucleotide_Type"] = df_curated_PRJEB64259["Sample_accession"].map(sample_accession_nucleotide_map)

PRJ_supp_data_path = "/content/drive/Shareddrives/Meta2/Metadata/Manual_metadata/PRJEB42572.xlsx"
supp_data = pd.read_excel(PRJ_supp_data_path)

age_map = supp_data.set_index("Sample_accession").to_dict()["Age"]
#clean age map
#if not a number, make NA
new_age_map = {}

for key in age_map:
  if str(age_map[key]).isnumeric():
    new_age_map[key] = age_map[key]
  else:
    new_age_map[key] = np.nan

sex_map = supp_data.set_index("Sample_accession").to_dict()["Sex"]

for key in sex_map:
  if (sex_map[key] != "Female") and (sex_map[key] != "Male"):
    sex_map[key] = np.nan

diet_lifestyle_map = supp_data.set_index("Sample_accession").to_dict()["Ethnic_Group"]

for key in diet_lifestyle_map:
  if diet_lifestyle_map[key] != "Nzime" and diet_lifestyle_map[key] != "Baka":
    diet_lifestyle_map[key] = np.nan

#create mask for age categories
age_conditions = [
    df_curated_PRJEB64259["Age"].between(0, 2),
    df_curated_PRJEB64259["Age"].between(3,5),
    df_curated_PRJEB64259["Age"].between(6,17),
    df_curated_PRJEB64259["Age"].between(18,39),
    df_curated_PRJEB64259["Age"].between(40,64),
    df_curated_PRJEB64259["Age"] >= 65
]

age_choices = ["Infant", "Child", "Adolescent", "Young_adult", "Middle_age", "Elderly"]

health_status_map = supp_data.set_index("Sample_accession").to_dict()["Root_visible"]
for key in health_status_map:
  if not pd.isna(health_status_map[key]):
    health_status_map[key] = "Root visible"
  else:
    health_status_map[key] = np.nan

df_curated_PRJEB64259["Health_status"] = df_curated_PRJEB64259["Sample_accession"].map(health_status_map)
df_curated_PRJEB64259["Diet"] = df_curated["Sample_accession"].map(diet_lifestyle_map)
df_curated_PRJEB64259["Lifestyle"] = df_curated["Sample_accession"].map(diet_lifestyle_map)
df_curated_PRJEB64259["Age"] = df_curated_PRJEB64259["Sample_accession"].map(new_age_map)
df_curated_PRJEB64259["Sex"] = df_curated_PRJEB64259["Sample_accession"].map(sex_map)
df_curated_PRJEB64259["Location"] = "Africa"
df_curated_PRJEB64259["Body_site"] = "oral"
df_curated_PRJEB64259["Age_category"] = np.select(age_conditions, age_choices, default="unknown")
df_curated_PRJEB64259["Age_category"] = df_curated_PRJEB64259["Age_category"].replace("unknown", np.nan)
df_curated_PRJEB64259["Body_site_core"] = "oral"

df_curated_PRJEB64259.to_csv("/content/drive/Shareddrives/Meta2/Metadata/Final_Curated_Out/PRJEB64259.csv", index = None)